name: Test Build

on: [push]

jobs:
  mock-api-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Clone smartsheet/smartsheet-sdk-tests PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'smartsheet'
          repository: 'smartsheet-sdk-tests'
          access-token: ${{ secrets.SDK_TEST_ACCESS_TOKEN }}
      - name: Setup mock API
        run: |
          smartsheet-sdk-tests/travis_scripts/install_wiremock.sh
          smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
      - name: Run coverage
        run: |
          npm run coverage
          npm run report-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}